[package]
name = "oil-lang"
version = "2.2.0"
authors = ["serprex"]
license = "MIT"
repository = "https://github.com/serprex/oilrs"
description = "Implementation of OIL"

[dependencies]
fnv = "1.0.5"
rand = "0.3.15"

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"
