[package]
name = "oil-lang"
version = "2.4.0"
authors = ["serprex"]
license = "MIT"
repository = "https://github.com/serprex/oilrs"
description = "Implementation of OIL"

[dependencies]
fnv = "1.0.7"
rand = "0.7.3"

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"
