[package]
name = "oilrs"
version = "0.1.0"
authors = ["serprex"]
license = "MIT"
repository = "https://github.com/serprex/oilrs"

[dependencies]
fnv = "1.0.5"
rand = "0.3.15"

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"
