[package]
name = "oil-lang"
version = "2.4.0"
authors = ["serprex"]
license = "MIT"
repository = "https://github.com/serprex/oilrs"
description = "Implementation of OIL"
edition = "2018"

[dependencies]
fxhash = "0.2"
rand = "0.7"

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"
