[package]
name = "oil-lang"
version = "2.3.0"
authors = ["serprex"]
license = "MIT"
repository = "https://github.com/serprex/oilrs"
description = "Implementation of OIL"

[dependencies]
fnv = "1.0.6"
rand = "0.5"

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"
